export function buildEnv(s) {
  const lines = [
    '# Generated by the CraftKeeper compose generator.',
    '# Keep this file OUT of version control — it holds real secrets.',
    '',
    `CRAFTKEEPER_APP_KEY=${s.secrets.appKey}`,
    `CRAFTKEEPER_APP_URL=${s.domain}`,
    '',
    '# RCON password. Not read automatically by the stack — copy this value into',
    '# /minecraft/server.properties (rcon.password=...) AND into CraftKeeper',
    "# onboarding's RCON step. See README.md.",
    `CRAFTKEEPER_RCON_PASSWORD=${s.secrets.rconPassword}`,
  ];
  if (s.realtime) {
    lines.push(
      '',
      '# Laravel Reverb (realtime console). REVERB_APP_SECRET must stay private.',
      `REVERB_APP_ID=${s.secrets.reverbAppId}`,
      `REVERB_APP_KEY=${s.secrets.reverbAppKey}`,
      `REVERB_APP_SECRET=${s.secrets.reverbAppSecret}`,
    );
  }
  return lines.join('\n') + '\n';
}
