import { buildNextSteps } from './steps.js';

export function buildReadme(s) {
  const services = [
    'CraftKeeper control panel',
    'Legendary Java Minecraft (Geyser + Floodgate)',
  ];
  if (s.pluginUpdater) services.push('Minecraft plugin updater (runs once before the server starts)');
  if (s.fileBrowser) services.push('File Browser (web file manager for the server volume)');

  return [
    '# CraftKeeper stack',
    '',
    'Generated by the CraftKeeper compose generator.',
    '',
    '## What this stack runs',
    '',
    ...services.map((line) => `- ${line}`),
    '',
    '## Files',
    '',
    '- `compose.yml` — the Docker Compose definition.',
    '- `.env` — secrets and settings. **Keep this out of version control.**',
    '',
    buildNextSteps(s),
    '## Security note',
    '',
    `The \`.env\` file contains a freshly generated application key${s.realtime ? ' and Reverb secret' : ''}.`,
    'Treat it as sensitive and never commit it to a repository.',
    '',
  ].join('\n');
}
