<?php

namespace App\Http\Controllers;

use App\Support\BackupService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\File;
use Inertia\Inertia;
use Inertia\Response;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Task 19's Settings > Backups page: create, list, download, and delete
 * App\Support\BackupService archives under {data_root}/backups. There is
 * deliberately no web "restore" action here — restoring means replacing
 * the running application's own database file, which this V1 does as a
 * manual operational step (stop the container, place the downloaded
 * archive's database.sqlite at the fresh {data_root}, start again) rather
 * than a self-service button that would need to interrupt the very
 * request serving it. App\Support\BackupService::restore() is the tested,
 * reusable primitive that operational step (or a future guided restore
 * UI) is built on.
 */
class BackupController extends Controller
{
    /**
     * Backup filenames are always generated by App\Support\BackupService
     * itself as `backup-{Ymd-His}-{8 hex chars}.zip` — this is the ONLY
     * shape ever accepted back from a route parameter, so a request for
     * `../../etc/passwd` (or any other traversal attempt) 404s here
     * before ever touching the filesystem.
     */
    private const FILENAME_PATTERN = '/^backup-\d{8}-\d{6}-[0-9a-f]{8}\.zip$/';

    public function __construct(
        private readonly BackupService $backups,
    ) {}

    public function index(): Response
    {
        return Inertia::render('settings/backups', [
            'backups' => $this->listBackups(),
        ]);
    }

    public function store(): RedirectResponse
    {
        $this->backups->create();

        Inertia::flash('toast', ['type' => 'success', 'message' => 'Backup created.']);

        return redirect('/settings/backups');
    }

    public function download(string $backup): BinaryFileResponse
    {
        $path = $this->resolveBackupPath($backup);

        return response()->download($path, $backup);
    }

    public function destroy(string $backup): RedirectResponse
    {
        $path = $this->resolveBackupPath($backup);

        File::delete($path);

        Inertia::flash('toast', ['type' => 'info', 'message' => 'Backup deleted.']);

        return redirect('/settings/backups');
    }

    /**
     * @return list<array{name: string, sizeBytes: int, createdAt: string}>
     */
    private function listBackups(): array
    {
        $dir = $this->backupsDir();

        if (! File::isDirectory($dir)) {
            return [];
        }

        $entries = [];

        foreach (File::files($dir) as $file) {
            $name = $file->getFilename();

            if (preg_match(self::FILENAME_PATTERN, $name) !== 1) {
                continue;
            }

            $entries[] = [
                'name' => $name,
                'sizeBytes' => $file->getSize(),
                'createdAt' => date(DATE_ATOM, $file->getMTime()),
            ];
        }

        usort($entries, fn (array $a, array $b) => $b['createdAt'] <=> $a['createdAt']);

        return $entries;
    }

    private function resolveBackupPath(string $backup): string
    {
        if (preg_match(self::FILENAME_PATTERN, $backup) !== 1) {
            throw new NotFoundHttpException('Backup not found.');
        }

        $path = $this->backupsDir().'/'.$backup;

        if (! File::exists($path)) {
            throw new NotFoundHttpException('Backup not found.');
        }

        return $path;
    }

    private function backupsDir(): string
    {
        return rtrim((string) config('craftkeeper.data_root'), '/').'/backups';
    }
}
